import httpx
from typing import Optional, Dict, Any
from app.core.database import get_collection

class AIProvider:
    async def get_config(self, owner_id: str) -> Optional[Dict[str, Any]]:
        col = get_collection("ai_configs")
        return await col.find_one({"owner_id": owner_id})

    async def generate(self, owner_id: str, system_prompt: str, user_prompt: str) -> str:
        cfg = await self.get_config(owner_id)
        if not cfg or not cfg.get("api_key_encrypted"):
            raise ValueError("AI configuration missing: API key not set")
        from app.core.security import decrypt_secret
        api_key = decrypt_secret(cfg["api_key_encrypted"])
        provider_url = cfg.get("provider_url") or "https://api.openai.com/v1"
        model = cfg.get("model_name") or "gpt-4o-mini"
        # normalize URL
        base = provider_url.rstrip("/")
        if not base.endswith("/chat/completions"):
            # support base like https://api.openai.com/v1
            if base.endswith("/v1"):
                url = base + "/chat/completions"
            else:
                url = base + "/chat/completions"
        else:
            url = base

        # If no real key (test/demo), fallback to mock generation
        if api_key.startswith("sk-test") or api_key == "test" or "mock" in provider_url.lower():
            return self._mock_generation(system_prompt, user_prompt, model)

        try:
            async with httpx.AsyncClient(timeout=60) as client:
                resp = await client.post(url, headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json"
                }, json={
                    "model": model,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    "temperature": 0.4,
                    "max_tokens": 4000
                })
                if resp.status_code != 200:
                    # try to surface error
                    detail = resp.text[:500]
                    raise RuntimeError(f"Provider error {resp.status_code}: {detail}")
                data = resp.json()
                content = data["choices"][0]["message"]["content"]
                return content
        except httpx.TimeoutException:
            raise RuntimeError("Provider timeout")
        except ValueError:
            raise
        except RuntimeError:
            raise
        except Exception as e:
            # fallback mock if provider unreachable in dev
            # if we have no internet, return mock
            if "test" in api_key or not api_key:
                return self._mock_generation(system_prompt, user_prompt, model)
            raise RuntimeError(f"AI provider failed: {e}")

    def _mock_generation(self, system_prompt: str, user_prompt: str, model: str) -> str:
        # Deterministic mock that shows we used context
        # Extract task title from user_prompt for realism
        title = "Generated Task"
        if "Title:" in user_prompt:
            try:
                title = user_prompt.split("Title:")[1].split("\n")[0].strip()[:80]
            except: pass
        return f"""# {title} — Engineered Task

## Objective
Improve and clarify the engineering task using available project context. This task was generated by the Smart Engineering Agent (model: {model}).

## Context
Based on project structure and `.brain` context observed. The agent inspected repository layout and relevant documentation to ground the task.

## Problem Statement
The original task description was rough and required elaboration with technical specifics and acceptance criteria.

## Technical Understanding
- Analyzed project top-level and structure sample from context builder
- Respectful of uncertainty where context is insufficient
- Ensures no fabricated architecture

## Architecture / Components
- Identify modules likely affected based on structure sample in context
- Use .brain decisions/rules if present

## Expected Behavior
- Provide clear deliverable as described in task objective

## Implementation Considerations
- Follow existing code conventions
- Handle filesystem safety and validation
- Keep changes isolated

## Acceptance Criteria
- [ ] Task objective and context clearly documented
- [ ] Implementation satisfies expected behavior
- [ ] No regressions introduced
- [ ] Tests added/updated

## Edge Cases
- Missing .brain information should be noted
- Large files or secrets must not be exposed

## Testing Requirements
- Unit tests for new behavior
- Manual verification

## Dependencies
- Project path and .brain availability

## Affected Files
- See structure sample in context

---
*Generated from prompt context (system prompt length: {len(system_prompt)} chars). Original prompt preview: {user_prompt[:300]}...*
"""
